version: 0.2

batch:
  fast-fail: false 
  build-fanout:
    parallelism: 3
    ignore-failure: false
    
phases:
  install:
    commands:
      - npm install jest-junit --save-dev
  pre_build:
    commands:
      - echo 'prebuild'
  build:
    commands:
      - echo "Running codebuild-tests-run command using CODEBUILD_CURRENT_SHARD_FILES"
      - codebuild-tests-run --test-command 'npx jest --runInBand --coverage --testPathPattern=$(echo "$CODEBUILD_CURRENT_SHARD_FILES" | tr "\n" " ")' --files-search "codebuild-glob-search '**/_tests_/calculator/**/*.test.js'" --sharding-strategy 'equal-distribution'
         
  post_build:
    commands:
      - codebuild-glob-search '**/*.xml'  
      - echo "Running post-build steps..."
      - echo "Build completed on `date`"


reports:
  failed-case-t:
    files:
      - "**/*"
    base-directory: 'test-reports'
    file-format: JunitXml
  failed-case-cc:
    files:
      - "**/*"
    base-directory: 'coverage'
    file-format: CLOVERXML

artifacts:
  files:
    - 'test-reports/**/*'
    - 'coverage/**/*'
  name: build-reports-$(date +%Y-%m-%d)
